jenkins:
  image: abstracttechnology/docker-jenkins:latest
  ports:
    - '8080:8080'
    - '50000:50000'

  volumes_from:
    - jenkinsdata

  # links:
  #   - 'dockersocat:dockersocat'


jenkinsdata:
  image: abstracttechnology/docker-jenkins:latest


# dockersocat:
#   image: sequenceiq/socat:latest
# volumes:
#    - "/var/run/docker.sock:/var/run/docker.sock"
# --privileged=true
